// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkQp8B6iw_jv8wAA8Yct-30vb3Gc7U390',
    appId: '1:918866269399:web:fcabf9916e70e7ca554c92',
    messagingSenderId: '918866269399',
    projectId: 'finishit-80d78',
    authDomain: 'finishit-80d78.firebaseapp.com',
    storageBucket: 'finishit-80d78.appspot.com',
    measurementId: 'G-412ZTYMY07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxYqu-Dh-1dBHCptkhOsaQWwq6oljoWBI',
    appId: '1:918866269399:android:774be8bbb8e3cd0c554c92',
    messagingSenderId: '918866269399',
    projectId: 'finishit-80d78',
    storageBucket: 'finishit-80d78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy8Remb1s2Smdsc7RKfA1OdXqdN8jnYwU',
    appId: '1:71459673029:ios:5409e35be05f353932f1ac',
    messagingSenderId: '71459673029',
    projectId: 'keep-up-83230',
    storageBucket: 'keep-up-83230.appspot.com',
    iosBundleId: 'com.example.keepup',
  );

}